#!/usr/bin/env bash
set -euo pipefail

################################################################################################
# File: ~/x400-software-pack/.git/hooks/post-merge
# Author: Andreas
# Date: 20251126
# Purpose: will be executed by git after git pull. Needed to install x400-software-pack.
################################################################################################
echo "This is $(basename "$0")"
echo " "

# Go to repo root
cd "$(dirname "$0")/../../"

# Optional logging
LOG_FILE="./git-post-update.log"
echo "[$(date)] post-merge hook running..." >> "$LOG_FILE"

# Run your script
bash ./scripts/copy_configs.sh --auto >> "$LOG_FILE" 2>&1

echo "[$(date)] post-merge hook done." >> "$LOG_FILE"