################################################################################################
# File: ~/klipper-backup/.env
# Author: klipper-backup / Andreas
# Date: 20250821
# Purpose: configuration of klipper-backup
#
# All information regarding .env can be found here: https://klipperbackup.xyz/configuration/
#
################################################################################################

################################################################################################
# GitHub settigns
################################################################################################
github_token=ghp_xxxxxxxxxxxxxxxx
github_username=USERNAME
github_repository=REPOSITORY
branch_name=main
commit_username=""
commit_email=""

################################################################################################
# Backup paths
################################################################################################
# Note: script.sh starts its search in $HOME which is /home/{username}/
# The array accepts folders or files like the following example:
#   backupPaths=( \
#   "printer_data/config/*" \
#   "printer_data/config/printer.cfg" \
#   )
# Using the above example the script will search for `/home/{username}/printer_data/config/*` and `/home/{username}/printer_data/config/printer.cfg`
# When backing up a folder you should always have `/*` at the end of the path so that files insde the folder are properly searched 

backupPaths=( \
"printer_data/config/*" \
"Klipper-Adaptive-Meshing-Purging/Configuration/*" \
"mainsail-config/client.cfg" \
"moonraker-timelapse/klipper_macro/timelapse.cfg" \
)

# NOT included due to credentials:  "$HOME/KlipperBackup/.env" \
# ??? Eryone famr3D config file 

# ??? How to backup this file?
#   "/etc/network/interfaces.d/can0"


################################################################################################
# Exlude files
################################################################################################
# Array of strings in .gitignore pattern git format https://git-scm.com/docs/gitignore#_pattern_format for files that should not be uploaded to the remote repo
# New additions must be enclosed in double quotes and should follow the pattern format as noted in the above link
exclude=( \
"*.swp" \
"*.tmp" \
"printer-[0-9]*_[0-9]*.cfg" \
"*.bak" \
"*.bkp" \
"*.csv" \
"*.zip" \
)